GET http://localhost:3003/

###

GET http://localhost:3003/students/all

### 

POST http://localhost:3003/student/001
Content-Type: application/json

{
    "class_id": 001
}

###

POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Joana",
    "email": "joaninha@hotmail.com",
    "birthDate": "10/10/1990"
}

###

POST http://localhost:3003/createClass
Content-Type: application/json

{
    "name": "Dumont", 
    "initialDate": "2021-01-01", 
    "finalDate": "2021000000-05-17", 
    "classModule": "6"
}