
GET http://localhost:3003/students/all

### 

POST http://localhost:3003/student/001
Content-Type: application/json

{
    "class_id": 001
}

###

POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Marcelino Sandroni",
    "email": "marcelino@hotmail.com",
    "birthDate": "1991-08-20"
}

###
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "Amandinha",
    "email": "Amandinha@gmail.com",
    "birthDate": "1994/07/17"
}

###

POST http://localhost:3003/students-class/4
Content-Type: application/json

{
    "class_id": 500
}